### PR TITLE
Upgrade Chrome and fix Chimp from failing without a proper return code

### PR DESCRIPTION
**Pull request by rsshilli**
This PR contains fixes for the following issues:
* TheBrainFamily#138 Support latest version of Chrome!
* TheBrainFamily#117 Hooks errors fix for #687 (now #113)
* TheBrainFamily#113 Saucelabs failure does not make chimp exit non-zero

### CODE REVIEW

**Comment by lgandecki** [comment]
Thank you so much. @lucetius could you please look through this and verify?

**Comment by rsshilli** [comment]
Oh, crap.  I didn't mean for the dist directory stuff to get merged into this PR.

**Comment by rsshilli** [comment]
OK.  It's better now.  Now it also deploys correctly from my Github repo.

**Comment by lgandecki** [comment]
@rsshilli  Thanks! I took your branch and tried to apply it to our current version with a newer chrome version, it causes problems on circleci with one of our large projects that has ~1000 tests. It seems that it consumes much more memory which kills our app. We need to investigate more before we bump it, as it could cause similar problems to other people. 
Meanwhile - do you have a specific usecase where you need a newer chromedriver?

**Comment by rsshilli** [comment]
Yes, PDFs didn't load correctly in Chrome 74 with Chromedriver 2.46.  I don't remember exactly what was the issue, but upgrading to the latest Chromedriver fixed it.

I actualy think we should extract the version of Chromedriver from Chimpy's package.json.  It looks like it used to come from `chimp.js`.

**Comment by rsshilli** [comment]
FWIW, I synced down the latest changes today in 1.2.0 and upgraded everything to Chrome 76, which I published as [1.2.1](https://www.npmjs.com/package/cherry-chimpy/v/1.2.1).   I'd still love to get this merged in.

**Comment by lgandecki** [comment]
what's different about the cherry-chromedriver? We've now made it possible to just install any chromedriver as dependency and that should be picked up. But that won't work with a package that has a different name (like "cherry-chromedriver") :)

**Comment by rsshilli** [comment]
Chrome 77 was out for a good week before NPM was updated with Chromedriver 77 and we had issues on the latest Chrome so we were forced to make our own repo just for a few days until the `chromedriver` package was updated. It's not permanent (we hope).

**Comment by rsshilli** [comment]
Also, how do I use any Chromedriver version now?

**Comment by rsshilli** [comment]
I closed this because it's too different now. I'm going to open new PRs.

**Pull request closed without merging**
